/*
 * Plain-data product catalog used by the seed script.
 * Mirrors the original frontend catalog (pvabrand-app/src/data/products.js) but
 * without any React/icon imports, so it can run on the backend. UI-only fields
 * (iconKey, gradient, badge, deliveryTime, features, originalPrice, …) are stored
 * on each Product's `specifications` so the storefront renders identically.
 */

const categories = [
  { id: 'social', name: 'Social Media' },
  { id: 'email', name: 'Email Accounts' },
  { id: 'finance', name: 'Finance & Crypto' },
  { id: 'streaming', name: 'Streaming & Entertainment' },
  { id: 'gaming', name: 'Gaming' },
  { id: 'productivity', name: 'Productivity & Cloud' },
  { id: 'smtp', name: 'SMTP Services' },
  { id: 'ecommerce', name: 'E-Commerce' },
]

const products = [
  { name: 'Instagram PVA Accounts', slug: 'instagram-pva-accounts', category: 'social', iconKey: 'instagram', shortDescription: 'Verified Instagram accounts with profile pictures, posts, and phone verification for instant use.', description: 'Get fully verified Instagram PVA (Phone Verified Accounts) ready for marketing, engagement, and business use. Each account comes with a profile picture, bio, and phone verification.', price: 4.99, originalPrice: 7.99, rating: 4.8, reviews: 2847, stock: 1500, deliveryType: 'Instant', deliveryTime: '0-5 minutes', badge: 'Best Seller', badgeColor: 'bg-green-500', gradient: 'from-pink-500 via-purple-500 to-indigo-500', features: ['Phone Verified', 'Profile Picture', 'Email Verified', 'Ready to Use'], minOrder: 10, maxOrder: 500 },
  { name: 'Gmail PVA Accounts', slug: 'gmail-pva-accounts', category: 'email', iconKey: 'gmail', shortDescription: 'Fresh Gmail accounts with recovery email and phone verification for professional use.', description: 'Premium quality Gmail accounts with full phone verification. Perfect for business communication, marketing campaigns, and account registrations.', price: 2.49, originalPrice: 4.99, rating: 4.9, reviews: 5621, stock: 3000, deliveryType: 'Instant', deliveryTime: '0-5 minutes', badge: 'Top Rated', badgeColor: 'bg-blue-500', gradient: 'from-red-400 via-red-500 to-red-600', features: ['Phone Verified', 'Recovery Email', 'Fresh Accounts', 'High Quality'], minOrder: 20, maxOrder: 1000 },
  { name: 'TikTok PVA Accounts', slug: 'tiktok-pva-accounts', category: 'social', iconKey: 'tiktok', shortDescription: 'Aged TikTok accounts with followers and engagement for content creators.', description: 'Get established TikTok accounts with phone verification and existing engagement. Ideal for content creators, influencers, and marketing agencies.', price: 5.99, originalPrice: 9.99, rating: 4.7, reviews: 1923, stock: 800, deliveryType: 'Instant', deliveryTime: '0-10 minutes', badge: 'Popular', badgeColor: 'bg-purple-500', gradient: 'from-black via-gray-800 to-pink-500', features: ['Phone Verified', 'Aged Account', 'Followers Included', 'Email Verified'], minOrder: 5, maxOrder: 200 },
  { name: 'LinkedIn PVA Accounts', slug: 'linkedin-pva-accounts', category: 'social', iconKey: 'linkedin', shortDescription: 'Professional LinkedIn accounts with connections and complete profiles.', description: 'Premium LinkedIn accounts with professional profiles, connections, and phone verification. Perfect for B2B marketing and professional networking.', price: 8.99, originalPrice: 14.99, rating: 4.6, reviews: 876, stock: 500, deliveryType: 'Manual', deliveryTime: '1-24 hours', badge: 'Premium', badgeColor: 'bg-yellow-500', gradient: 'from-blue-600 to-blue-800', features: ['Phone Verified', 'Complete Profile', 'Connections', 'Professional'], minOrder: 5, maxOrder: 100 },
  { name: 'X / Twitter PVA Accounts', slug: 'x-twitter-pva-accounts', category: 'social', iconKey: 'twitter', shortDescription: 'Verified X/Twitter accounts with followers and established history.', description: 'Get established X (formerly Twitter) accounts with phone verification and follower base. Great for social media marketing and brand building.', price: 3.99, originalPrice: 6.99, rating: 4.7, reviews: 2156, stock: 1200, deliveryType: 'Instant', deliveryTime: '0-5 minutes', badge: 'Best Seller', badgeColor: 'bg-green-500', gradient: 'from-gray-700 to-black', features: ['Phone Verified', 'Aged Account', 'Followers', 'Email Verified'], minOrder: 10, maxOrder: 500 },
  { name: 'Facebook PVA Accounts', slug: 'facebook-pva-accounts', category: 'social', iconKey: 'facebook', shortDescription: 'Real Facebook accounts with friends, posts, and full phone verification.', description: 'Authentic Facebook accounts with established profiles, friend networks, and complete phone verification for advertising and marketing.', price: 3.49, originalPrice: 5.99, rating: 4.5, reviews: 3412, stock: 2000, deliveryType: 'Instant', deliveryTime: '0-10 minutes', badge: 'Popular', badgeColor: 'bg-purple-500', gradient: 'from-blue-600 to-blue-800', features: ['Phone Verified', 'Friends Added', 'Real Activity', 'Email Verified'], minOrder: 10, maxOrder: 500 },
  { name: 'YouTube PVA Accounts', slug: 'youtube-pva-accounts', category: 'social', iconKey: 'youtube', shortDescription: 'YouTube channels with subscribers and watch hours for monetization.', description: 'Established YouTube accounts with subscribers, watch hours, and phone verification. Perfect for content creators looking to boost their channels.', price: 12.99, originalPrice: 19.99, rating: 4.8, reviews: 654, stock: 300, deliveryType: 'Manual', deliveryTime: '1-12 hours', badge: 'Premium', badgeColor: 'bg-yellow-500', gradient: 'from-red-500 to-red-700', features: ['Phone Verified', 'Subscribers', 'Watch Hours', 'Monetization Ready'], minOrder: 1, maxOrder: 50 },
  { name: 'Reddit PVA Accounts', slug: 'reddit-pva-accounts', category: 'social', iconKey: 'reddit', shortDescription: 'Aged Reddit accounts with karma and email verification.', description: 'Established Reddit accounts with karma history and phone verification. Ideal for marketing, SEO, and community engagement.', price: 2.99, originalPrice: 4.99, rating: 4.6, reviews: 1287, stock: 900, deliveryType: 'Instant', deliveryTime: '0-5 minutes', badge: null, badgeColor: null, gradient: 'from-orange-500 to-red-600', features: ['Phone Verified', 'Karma History', 'Email Verified', 'Aged Account'], minOrder: 10, maxOrder: 300 },
  { name: 'Discord Accounts', slug: 'discord-accounts', category: 'social', iconKey: 'discord', shortDescription: 'Verified Discord accounts with email and phone verification.', description: 'Premium Discord accounts with full verification for server management, bot development, and community building.', price: 1.99, originalPrice: 3.49, rating: 4.5, reviews: 2034, stock: 2500, deliveryType: 'Instant', deliveryTime: '0-5 minutes', badge: 'Best Seller', badgeColor: 'bg-green-500', gradient: 'from-indigo-500 to-purple-600', features: ['Phone Verified', 'Email Verified', 'Ready to Use', 'High Quality'], minOrder: 10, maxOrder: 500 },
  { name: 'Spotify Premium Accounts', slug: 'spotify-premium-accounts', category: 'streaming', iconKey: 'spotify', shortDescription: 'Premium Spotify accounts with ad-free music and offline downloads.', description: 'Get Spotify Premium accounts with full access to millions of songs, ad-free listening, and offline downloads.', price: 6.99, originalPrice: 10.99, rating: 4.8, reviews: 4523, stock: 1800, deliveryType: 'Instant', deliveryTime: '0-5 minutes', badge: 'Best Seller', badgeColor: 'bg-green-500', gradient: 'from-green-500 to-green-700', features: ['Premium Access', 'Ad-Free Music', 'Offline Mode', 'Family Plan Available'], minOrder: 1, maxOrder: 100 },
  { name: 'Netflix Premium Accounts', slug: 'netflix-premium-accounts', category: 'streaming', iconKey: 'netflix', shortDescription: 'Netflix Premium accounts with 4K streaming and multiple profiles.', description: 'Premium Netflix accounts supporting 4K UHD streaming with multiple profiles and simultaneous device support.', price: 8.99, originalPrice: 15.99, rating: 4.7, reviews: 3876, stock: 1200, deliveryType: 'Instant', deliveryTime: '0-10 minutes', badge: 'Popular', badgeColor: 'bg-purple-500', gradient: 'from-red-600 to-red-800', features: ['4K UHD Streaming', 'Multiple Profiles', 'Simultaneous Streams', 'Premium Quality'], minOrder: 1, maxOrder: 50 },
  { name: 'Binance Accounts', slug: 'binance-accounts', category: 'finance', iconKey: 'binance', shortDescription: 'Verified Binance accounts with KYC for crypto trading.', description: 'Fully verified Binance accounts with KYC completion for seamless cryptocurrency trading and transactions.', price: 24.99, originalPrice: 39.99, rating: 4.9, reviews: 567, stock: 200, deliveryType: 'Manual', deliveryTime: '1-24 hours', badge: 'Premium', badgeColor: 'bg-yellow-500', gradient: 'from-yellow-400 to-yellow-600', features: ['KYC Verified', 'Full Access', 'Phone Verified', 'Secure'], minOrder: 1, maxOrder: 10 },
  { name: 'Coinbase Accounts', slug: 'coinbase-accounts', category: 'finance', iconKey: 'coinbase', shortDescription: 'Verified Coinbase accounts for secure cryptocurrency transactions.', description: 'Get fully verified Coinbase accounts with KYC for buying, selling, and transferring cryptocurrencies securely.', price: 19.99, originalPrice: 34.99, rating: 4.8, reviews: 423, stock: 150, deliveryType: 'Manual', deliveryTime: '1-24 hours', badge: 'Premium', badgeColor: 'bg-yellow-500', gradient: 'from-blue-500 to-blue-700', features: ['KYC Verified', 'Bank Linked', 'Full Access', 'Secure'], minOrder: 1, maxOrder: 10 },
  { name: 'PayPal Accounts', slug: 'paypal-accounts', category: 'finance', iconKey: 'paypal', shortDescription: 'Verified PayPal accounts with email and phone verification.', description: 'Premium PayPal accounts with full verification for online payments, transfers, and business transactions.', price: 14.99, originalPrice: 24.99, rating: 4.7, reviews: 1876, stock: 600, deliveryType: 'Manual', deliveryTime: '1-12 hours', badge: 'Popular', badgeColor: 'bg-purple-500', gradient: 'from-blue-400 to-blue-600', features: ['Email Verified', 'Phone Verified', 'Full Access', 'Transaction Ready'], minOrder: 1, maxOrder: 25 },
  { name: 'Amazon Accounts', slug: 'amazon-accounts', category: 'ecommerce', iconKey: 'amazon', shortDescription: 'Verified Amazon accounts with Prime membership options.', description: 'Get verified Amazon accounts with full access for shopping, seller activities, and Prime membership benefits.', price: 9.99, originalPrice: 16.99, rating: 4.6, reviews: 2345, stock: 700, deliveryType: 'Manual', deliveryTime: '1-12 hours', badge: 'Best Seller', badgeColor: 'bg-green-500', gradient: 'from-orange-400 to-yellow-500', features: ['Email Verified', 'Full Access', 'Prime Available', 'Secure'], minOrder: 1, maxOrder: 25 },
  { name: 'Apple ID Accounts', slug: 'apple-id-accounts', category: 'productivity', iconKey: 'apple', shortDescription: 'Verified Apple IDs with iCloud access for Apple ecosystem.', description: 'Premium Apple ID accounts with full iCloud access, App Store privileges, and Apple ecosystem integration.', price: 7.99, originalPrice: 12.99, rating: 4.7, reviews: 1543, stock: 400, deliveryType: 'Manual', deliveryTime: '1-12 hours', badge: null, badgeColor: null, gradient: 'from-gray-400 to-gray-600', features: ['iCloud Access', 'App Store', 'Full Control', 'Secure'], minOrder: 1, maxOrder: 20 },
  { name: 'iCloud Accounts', slug: 'icloud-accounts', category: 'productivity', iconKey: 'icloud', shortDescription: 'Clean iCloud accounts with storage and Apple services.', description: 'Fresh iCloud accounts with storage space and full Apple services access for backup, sync, and storage.', price: 5.99, originalPrice: 9.99, rating: 4.6, reviews: 987, stock: 500, deliveryType: 'Instant', deliveryTime: '0-10 minutes', badge: null, badgeColor: null, gradient: 'from-sky-400 to-blue-500', features: ['Storage Included', 'Apple Services', 'Clean Account', 'Verified'], minOrder: 1, maxOrder: 50 },
  { name: 'Microsoft Accounts', slug: 'microsoft-accounts', category: 'productivity', iconKey: 'microsoft', shortDescription: 'Verified Microsoft accounts with Office 365 and OneDrive access.', description: 'Premium Microsoft accounts with Office 365 access, OneDrive storage, and full Microsoft ecosystem integration.', price: 6.99, originalPrice: 11.99, rating: 4.7, reviews: 1234, stock: 600, deliveryType: 'Instant', deliveryTime: '0-10 minutes', badge: null, badgeColor: null, gradient: 'from-blue-500 to-blue-700', features: ['Office 365', 'OneDrive', 'Full Access', 'Verified'], minOrder: 1, maxOrder: 50 },
  { name: 'Gmail SMTP Service', slug: 'gmail-smtp-service', category: 'smtp', iconKey: 'gmail', shortDescription: 'Gmail SMTP configuration for automated email sending campaigns.', description: 'Professional Gmail SMTP service setup for automated email campaigns, transactional emails, and marketing communications.', price: 3.99, originalPrice: 6.99, rating: 4.8, reviews: 3210, stock: 2000, deliveryType: 'Instant', deliveryTime: '0-5 minutes', badge: 'Best Seller', badgeColor: 'bg-green-500', gradient: 'from-red-500 to-orange-500', features: ['SMTP Access', 'API Ready', 'Bulk Sending', 'High Deliverability'], minOrder: 1, maxOrder: 100 },
  { name: 'iCloud SMTP Service', slug: 'icloud-smtp-service', category: 'smtp', iconKey: 'icloud', shortDescription: 'iCloud SMTP relay for reliable email delivery and automation.', description: 'iCloud SMTP relay service for reliable email delivery, perfect for transactional emails and automated notifications.', price: 4.99, originalPrice: 8.99, rating: 4.7, reviews: 876, stock: 800, deliveryType: 'Instant', deliveryTime: '0-10 minutes', badge: 'Premium', badgeColor: 'bg-yellow-500', gradient: 'from-sky-400 to-indigo-500', features: ['SMTP Relay', 'High Reliability', 'Apple Ecosystem', 'Verified'], minOrder: 1, maxOrder: 50 },
  { name: 'Telegram Accounts', slug: 'telegram-accounts', category: 'social', iconKey: 'telegram', shortDescription: 'Verified Telegram accounts with phone number verification.', description: 'Premium Telegram accounts with phone verification for personal use, groups, channels, and business communication.', price: 1.99, originalPrice: 3.49, rating: 4.6, reviews: 2876, stock: 3000, deliveryType: 'Instant', deliveryTime: '0-5 minutes', badge: 'Best Seller', badgeColor: 'bg-green-500', gradient: 'from-blue-400 to-blue-600', features: ['Phone Verified', 'Premium Ready', 'Instant Delivery', 'Secure'], minOrder: 10, maxOrder: 1000 },
  { name: 'WhatsApp Accounts', slug: 'whatsapp-accounts', category: 'social', iconKey: 'whatsapp', shortDescription: 'Verified WhatsApp accounts for business and personal messaging.', description: 'Get verified WhatsApp accounts for business marketing, bulk messaging, and customer communication.', price: 3.49, originalPrice: 5.99, rating: 4.7, reviews: 1654, stock: 900, deliveryType: 'Instant', deliveryTime: '0-10 minutes', badge: 'Popular', badgeColor: 'bg-purple-500', gradient: 'from-green-400 to-green-600', features: ['Phone Verified', 'Business Ready', 'Instant Use', 'Full Access'], minOrder: 5, maxOrder: 200 },
]

module.exports = { categories, products }
